title: Your awesome title
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: dre_dpittaa
instagram:  dre_spittaa
twitter_link: https://twitter.com/Dre_Spittaa
instagram_link: https://www.instagram.com/dre_spittaa/?hl=en
facebook_link: https://www.facebook.com/DreSpittaa
soundcloud_link: https://soundcloud.com/dre-spittaa-verse
youtube_link: https://www.youtube.com/user/DreSpittaaverse

email: dre spittaa verse (at) gmail (dot) com

collections:
  albums:
    output: true
    permalink: /:title/
# Build Settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
